server:
    port: 9090

spring:
    datasource:
       url: jdbc:postgresql://localhost:5432/ndovuheights
       username: postgres
       password: 1234
       hikari:
        auto-commit: false
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
       ddl-auto: update
